name: VoxelFurniture
version: ${project.version}
main: org.voxelhorizons.furniture.VoxelFurniture
api-version: '1.13'
depend: [VoxelCore]

commands:
  voxelfurniture:
    description: VoxelFurniture administration and debugging
    aliases: [vf]
    permission: voxelfurniture.use

permissions:
  voxelfurniture.dye:
    default: true
  voxelfurniture.use:
    default: true
  voxelfurniture.place:
    default: true
  voxelfurniture.break:
    default: true
  voxelfurniture.sit:
    default: true
  voxelfurniture.inventory:
    default: true
  voxelfurniture.admin:
    default: op
  voxelfurniture.admin.give:
    default: op
  voxelfurniture.admin.list:
    default: op
  voxelfurniture.admin.remove:
    default: op
  voxelfurniture.admin.cleanup:
    default: op
